### ISSUE TITLE
Pestaña autorización

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#15]
En la pestaña "Autorización" de la ficha de Persona creo que sería más interesante cambiarle el caption por "Documentación" o "Adjuntos" para que sea más descriptivo: podemos adjuntar autorizaciones, las notas, una nómina, etc, asociadas a proyectos en los que participa una persona o no.

**Comment by mariogarcia** [comment]
Hola \o/

Vale esto es sencillo, voy a crear un milestone para ver que meto en el y para cuando hago un nuevo release.
