### ISSUE TITLE
Proceso: posible fallo permisos

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#18]
Usuarios sin permiso de administración pueden editar "Procesos" que han creado otros usuarios. En principio cada usuario debería poder editar los Procesos que ha creado, pero únicamente ver los que han creado otros usuarios, ¿no?

Gracias :)

**Comment by mariogarcia** [comment]
Sip hay que repasar los permisos. En principio el "capar" los permisos no deberia llevar mucho tiempo.

Esto me recuerda que teniamos que empezar a documentar la aplicacion. He estado mirando varios generadores de documentacion estaticos y tengo un candidato que me gusta basado en markdown sin necesidad de tener instalado nada en ningun sitio. Igual hasta nos sirve para tener una landing. Cuando haya hecho una prueba os lo muestro a ver que os parece, y empezamos a documentar cosas como esta.

**Comment by mariogarcia** [comment]
Tengo que cambiar el modelo, ya que tenemos que no consta quien ha creado ese registro.

Supongo que habra que ir haciendolo para procesos, documentos...etc. Voy a hacer un listado.

**Comment by mariogarcia** [comment]
Wow, esta version si que va a ser importante :)

Los registros de personas, procesos, proyectos... no tenian un registro de quien los habia creado ni quien habia sido la ultima persona en actualizarlos de manera que no se podia realizar la comprobacion de que solo aquellos que lo habian creado pudieran editar el registro. **Ahora si que se va a actualizar tanto quien lo ha creado como quien ha sido el ultimo usuario en actualizarlo**. 

Estoy corriendo las migraciones para asegurarme de que no se rompera nada al actualizar el modelo y lo unico es que me confirmes lo siguiente @joseanrey 

- La **edicion e inabilitacion de una persona** solo se podra realizar por el usuario que creo el registro o el administrador
- La **edicion y borrado de procesos de una persona** solo se podra realizar por el usuario que creo el registro o el administrador
- La **edicion y borrado de documentos de una persona** solo se podra realizar por el usuario que creo el registro o el administrador 

Se me olvida alguna cosa ?

**Comment by joseanrey** [comment]
Hola!
Que bueno leer esto que cuentas, ganas de probarlo jejeje

Te voy confirmando según nos cuentas por correo electrónico, aunque yo lo dejaría tal y como propones:

- **Datos personales:** 
El creador: puede editar, e inhabilitar a la persona OK, aunque me surge una duda: puede suceder a menudo que el usuario que cree una ficha de persona no sea el referente real de esa persona nunca, con lo que la posibilidad de inhabilitar no tenga mucho sentido. Por ejemplo: el usuario X va a tener la posibilidad de inhabilitar dentro de Y años a una persona que ya ni recuerda quién es ni que fue el autor de su ficha. El usuario Z pedirá directamente al admin que lo inhabilite si no tiene permisos. Quizá le quitaría la posibilidad de inhabilitar.
El admin: puede editar, e inhabilitar a la persona OK
Otros: pueden editar y ver sólo los datos personales pero no pueden inhabilitar a la persona OK

- **Procesos de la persona:**
El creador: puede editar, ver y eliminar un proceso OK
El admin: puede editar, ver y eliminar un proceso OK
Otros: solo pueden ver un proceso OK

- **Documentos de la persona**
El creador: puede editar ver y eliminar un documento OK
El admin: puede editar ver y eliminar un documento OK
Otros: solo pueden descargarse un documento OK

**Comment by mariogarcia** [comment]
Me parece bien que solo el admin pueda deshabilitar a una persona.Vale pues perfecto, me pongo con ello.
