### ISSUE TITLE
Exportar CSV

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#19]
No sé si esto es fallo de la aplicación o mío. Al exportar un documento en CSV la codificación de caracteres no muestra correctamente tildes , ñ, etc

**Comment by mariogarcia** [comment]
He hecho una prueba y estoy viendo que importandolo con codificacion UTF-8 se ve bien:

![UTF-8](https://user-images.githubusercontent.com/1414131/99656425-279f2b80-2a5d-11eb-9bb3-ffcfb569656b.png)

Pero que si lo importo como ISO-8859-1 no se ve bien:

![ISO-8859-1](https://user-images.githubusercontent.com/1414131/99656494-3dacec00-2a5d-11eb-8942-569dcf431902.png)

Lo que puedo hacer es forzarlo a una codificacion determinada y documentar en algun sitio que se exporta con esa codificacion.

**Comment by mariogarcia** [comment]
He hecho los siguientes cambios:

- He forzado a que la exportacion sea siempre en UTF-8
- He cambiado el prefijo del fichero de exportacion a `liceo-XXX`
