### ISSUE TITLE
Falta Sexo y Género: Modelo Ficha Persona

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#20]
En la pestaña de administración puedo añadir Géneros (nosotros recogemos "Masculino", "Femenino" y "No se identifica"), pero luego en el formulario de Añadir Ficha de Persona aparece etiquetado como "Sexo", en lugar de "Género". Por otro lado, al guardar la ficha de Persona no se muestra ningún dato en la misma, aunque si editas la ficha el dato está recogido. Por lo que al exportar el CSV tampoco aparece la columna.

Le hemos dado una vuelta y sería interesante que la ficha de Persona pudiera recoger también Sexo (Hombre y Mujer) de forma adicional a Género. Desde el panel de administración se podrían añadir las opciones y al añadir Persona tendrías que completar Género y Sexo.

Así quedaría:

- Género. Opciones: Masculino, Femenino, No se identifica

- Sexo: Hombre, Mujer

Saludos :)

**Comment by mariogarcia** [comment]
Vale lo que voy a hacer es mantener el campo actual como `Sexo` que parece que es como se esta usando actualmente y asi mantenemos los datos actuales, y creare un nuevo campo `Genero` donde se pueda recoger realmente el genero con un campo mas en la base de datos.

**Comment by mariogarcia** [comment]
Necesito hacer una migracion @joseanrey  

Ahora se quedaria el campo de sexo vacio y es obligatorio. Pienso en dos opciones:

- A todos las personas que tuvieran como genero `Masculino` se les pone `Hombre` como sexo, `Mujer` a los de 'Femenino` y 'pendiente` a los de `No se identifica` y cuando se edite el perfil se pone el correcto.

- Se les pone `pendiente` a tod@s y cuando se edite la persona se pone el sexo correcto.

Con lo que me digais, cierro esta historia.

**Comment by mariogarcia** [comment]
Al final esta historia tenia mas trabajo del que parecia. Lo he dejado de la siguiente manera:

- He activado las migraciones de base de datos, ya que es necesario para poder gestionar de una manera seria los cambios del modelo de datos. Eso requerira una migracion **manual** en las instancias instaladas actualmente.

- Respecto a la migracion de los datos de genero y sexo, se dejara el dato que tuviera una persona en genero, y se dejara en pendiente el campo del sexo.

De todas maneras cuando vayais a instalar la nueva version lo vemos pormenorizadamente.

**Comment by joseanrey** [comment]
Perdona, pero me surge una duda recuperando este tema. En el listado de personas al exportar el CSV no aparece el Sexo de cada persona. Creo que esto ya lo hablamos, pero por si se nos ha olvidado para la próxima versión, para mostrar Sexo y Género.

**Comment by mariogarcia** [comment]
Ah bien visto! se me ha pasado. Voy a incluirlo

**Comment by mariogarcia** [comment]
Perdon entiendo que lo voy a incluir en la exportacion CSV. Quieres que lo incluya en el listado ? En todo caso, lo incluiria en los filtros (que ya tiene genero, agregaria el filtro de sexo). No recargaria mucho los datos que se muestran en el listado. Ya me dices

**Comment by joseanrey** [comment]
Si, en filtros y CSV yo creo que va bien con ambos. En el listado okey a dejarlo poco recargado.
