### ISSUE TITLE
Nueva funcionalidad: Calendario de citas

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#21]
Lo dejo por aquí para que no se nos pierda: sería interesante que cada profesional se pudiera "citar a personas" en un calendario en diferentes eventos en una agenda (para cualquier tipo de proceso). Por ejemplo, yo puedo asignar a la persona X en un día Y para un proceso que sería "Coordinación centro educativo" y luego otro día Z citar a la misma persona X para una "Entrevista individual". Luego cuando yo accedo al detalle de la cita puedo ir directamente al proceso asociado en la ficha de persona donde puedo escribir o leer el contenido de la misma. Si en cada cita yo puedo especificar el tiempo asignado a la misma podría hacer una consulta a la base de datos a final de año y saber cuánto tiempo he dedicado a cada diferente proceso individual por persona: podría saber cuántas horas de intervención individual hemos realizado, cuantas horas de coordinación con centros educativos, cuántas horas de coordinación con la trabajadora social, cuántas horas de entrevistas con toda la familia, etc.

**Comment by joseanrey** [comment]
Con esto se podría pintar en el dashboard una gráfica muy cuca con número de horas por tipo de proceso y día jajajaja

**Comment by joseanrey** [comment]
Repensando esta movida creo que no sería muy complicado. 

- Por un lado necesitaríamos en la tabla de procesos un campo de "duración" que podría ser nulo.
- Por otro lado en el frontend de liceo sería necesario añadir una opción para mostrar una vista con todos los procesos en un calendario para el usuario logado, con un enlace a su detalle en cada uno de ellos. El admin podría ver todos.
- Finalmente tendríamos que ser capaces de exportar en CSV todos los procesos para una persona particular con determinados filtros. Esto sería temporal para poder ir tratando la información, igual que el filtrado de personas.

**Comment by mariogarcia** [comment]
- En cuanto a la duracion me queda claro, probablemente pondria un campo HTML auto-formateado tipo 00:00:00.
- En cuanto a lo de mostrar todos los procesos en un calendario. **Crees que deberiamos cambiar el listado de procesos por un calendario, o son 2 vistas diferentes ?**
- En cuanto a los filtros, supongo que seria filtrar por cualquiera de las columnas que ahora mismo se muestran para los procesos no ?

**Comment by joseanrey** [comment]
Creo que el listado lo mantendría tal cual está, que puedas ver un listado de procesos dentro de cada ficha es muy útil y guarda coherencia con el listado de documentos. Ambos asociados a una persona. 

Lo que añadiría sería una vista nueva en el menú lateral como si fuera una "Agenda" (como calendario mensual o semanal) en el que el usuario pueda ver todos los últimos procesos (o los próximos) de las fichas de las personas de las cuales es referente, cada uno en su fecha, ya que además del referente también otro usuario de la aplicación puede añadir procesos a "mis personas", por así decirlo. De esta manera podría ver toda la información de mis casos que está sucediendo ahora mismo. No sé si me explico xD

**Comment by mariogarcia** [comment]
Entendido, creo que podemos empezar trabajar sobre esta propuesta :+1:

**Comment by mariogarcia** [comment]
A ver que te parece @joseanrey 

### Creacion de proceso

Cuando creas un proceso nuevo puedes crear el proceso para un dia determinado. Si no indicas nada diferente, se registra la fecha pero ninguna hora en concreto.

![create_process_allday](https://user-images.githubusercontent.com/1414131/102767737-53754000-4380-11eb-9bfe-1822582a3e35.png)

O establecer la hora a la que va tener lugar el proceso:

![create_process_set_hour](https://user-images.githubusercontent.com/1414131/102768346-5290de00-4381-11eb-85b2-f4a21eb6c7e7.png)

O si quieres establecer la hora de inicio y de fin:

![create_process_full_duration](https://user-images.githubusercontent.com/1414131/102768466-8409a980-4381-11eb-9dc4-095168b60c9b.png)

Cuando vuelves al listado tienes los procesos creados pero ahora puedes pulsar sobre **agenda** y eso te mostrara los procesos de ese usuario **OJO** creados por ti:

![create_process_goto_agenda](https://user-images.githubusercontent.com/1414131/102767735-52dca980-4380-11eb-9cd9-7c48268e9795.png)

Y se podra ir a la agenda filtrada por el usuario con el que estas tratando

![create_process_agenda](https://user-images.githubusercontent.com/1414131/102767733-52441300-4380-11eb-8847-edbd70789883.png)

A la agenda se puede acceder directamente desde el menu lateral.

![agenda_entry](https://user-images.githubusercontent.com/1414131/102768221-1a899b00-4381-11eb-97bf-cb27e092cee8.png)

### Filtrado de procesos

La agenda se puede filtrar por:

- personas
- proyectos
- tipo de procesos

![agenda_filter](https://user-images.githubusercontent.com/1414131/102768768-f67a8980-4381-11eb-8770-bde3d81627e8.png)

Tiene dos vistas:

- semanal
- mensual

Sobre la agenda se puede:

- Ver la descripcion de cada proceso
- Pulsar sobre el evento e ir al detalle del proceso en concreto

### Dudas

- Cuando cualquier usuario puede ver todos los procesos o solo aquellos que hayan creado ? He leido otra vez los comentarios anteriores, y dado que comentabas que uno de los filtros podria ser autor, entiendo que todos los trabajadores sociales deben poder tener visibilidad de los procesos del resto de trabajadores. Confirmame esto.

- La exportacion del CSV de los procesos de una persona, ahora mismo seria rapido el exportar desde el listado de procesos pudiendo exportar todos, o filtrarlos por proyecto. Si luego necesitamos filtrarlo por mas cosas, lo abordaria de cara a futuro ya que tendriamos que pensar en modificar esa pantalla o crear una nueva para poder mostrar los filtros correctamente.

**Comment by mariogarcia** [comment]
Te dejo un pantallazo de como quedaria lo de la exportacion CSV desde el listado de procesos

![process_export_csv](https://user-images.githubusercontent.com/1414131/102774375-24180080-438b-11eb-9421-bfd10411aa95.png)

Estaria exportando:

- O todos los procesos
- Aquellos que correspondan al proyecto seleccionado

**Comment by joseanrey** [comment]
Okey a todo,
me gusta mucho todo!

Por rizar el rizo, si cada tipo de proceso tuviera un color asociado (aleatorio o que yo pueda seleccionar al crear tipo de proceso) quizá quedaría más pintoresco el calendario. O quizá tendría más sentido asignar diferentes niveles de prioridad cuando agendas un proceso y que con esos niveles se muestren diferentes colores en el calendario. Bueno, todo esto no es prioritario en todo caso y podemos irlo pensando.

Respecto a tus dudas:

- Efectivamente, creo que sería útil que cualquier usuario pueda ver todos los procesos asociados a una persona independientemente de quién sea el autor. Facilita el flujo de información. Otra cosa sería editarlos, que igual es interesante que yo solo pueda editar los que yo he creado. Ahora mismo, por ejemplo (no sé si lo hemos cambiado para la 0.3) yo puedo ver todos los procesos creados por mí y los creados por otros usuarios y puedo editar todos, tanto si soy el autor como si no lo soy.
- Okey a lo del filtrado general. Está perfecto. Nos sive ya que teniendo un CSV con el listado de todos puedo quedarme solo con los que tienen tiempo asociado y jugar con esa información. Teniendo la posibilidad de exportar generalizada el filtrado más afinado no sería prioritario.

**Comment by mariogarcia** [comment]
Lo del color lo pense ayer XDXDXD.

Voy a cambiar primero lo que tiene que ver con el filtrado y luego veo lo de agregar un campo en tipos de proceso que sea "color". 

- Vale voy a cambiar lo de que cualquiera pueda filtrar por procesos creados por otras personas. **Por cierto** recuerda que en https://github.com/liceo-social/liceo/issues/18 modificamos los procesos para que solo los creadores y el administrador pudieran editar sus procesos, el resto solo pueden ver los procesos.

Lo que creo que voy a hacer tambien es **poner en el formulario de filtrado un checkbox que signifique "filtrar mis procesos"**. Es decir si hay varios usuarios que han creado procesos para X y yo quiero ver solo los mios para X seleccionaria "filtrar mis procesos" y seleccionaria a la persona X por ejemplo

- Lo del CSV ya esta hecho :)

**Comment by joseanrey** [comment]
Perfecto el filtro de Mis procesos! 
Sobre #18, ya decía yo que me sonaba que ya estaba corregido, llevamos un ritmo tan frenético de actualizaciones que no me doy cuenta xD
