### ISSUE TITLE
Nueva funcionalidad: Alertas por persona

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#22]
Que se puedan mostrar alertas vinculadas a la ficha de una persona cuando accedes a su ficha, quizá no asociadas a una fecha particular sino que se puedan mostrar hasta que su autor las desactive. Esto también podría mostrarse en un futuro dashboard de cada usuario. Por ejemplo: 

- Tipo: Alerta (Rojo)

- Contenido: "Falta documentación de padrón municipal."

- IdPersona: XXXXXX (Si pinchas en el enlace de su ID te lleva a la ficha de la persona)

Otro ejemplo:

- Tipo: Informativa (Azul)

- Contenido: "Va a faltar a las actividades porque está de viaje."

- IdPersona: XXXXXX (Si pinchas en el enlace de su ID te lleva a la ficha de la persona)

Bueno, quizá si que deberían tener una fecha para poder ordenarlas, o poder ordenarlas en función del peso de cada tipo de alerta. Habría que darle una vuelta jejeje

**Comment by mariogarcia** [comment]
@joseanrey  Lo he planteado de la siguiente manera a ver que te parece:

## Tipos de alertas

Un usuario puede tener tres tipos de alertas:

- Nota: Simplemente comentarios que dejan los profesionales
- Warning: A tener en cuenta pero que no requiere una atencion inmediata
- Peligro: Representa que se tomen acciones inmediatas

![alertas_creacion](https://user-images.githubusercontent.com/1414131/107517946-b4fea180-6bae-11eb-8637-1b0785fadfd7.png)

Las alertas ademas llevaran registrado:

- Cuando se crearon
- Cuando se actualizaron
- Quien lo creo
- Quien lo actualizo por ultima vez

## Ficha de persona

Habra una nueva pestana en la ficha de una persona donde se listaran, filtraran y se podran crear nuevas 

![alertas_listado](https://user-images.githubusercontent.com/1414131/107517704-605b2680-6bae-11eb-8627-5b321574f8ed.png)

## Dashboard

En los listados de nuevas personas se mostraran unos indicadores con el numero de alertas por tipo, si es que la persona tiene alguna.

![alertas_dashboard](https://user-images.githubusercontent.com/1414131/107517789-78cb4100-6bae-11eb-85ad-179e38b7277e.png)

Estos indicadores sirven para filtrar las alertas de esa persona. Al pulsar se mostraran las alertas de esa persona por el tipo seleccionado.

## Dudas

### Eliminacion de alertas

Cuando alguien resuelve una alerta, Queremos eliminarla ? Estaba pensando si para temas de estadistica, o de auditoria, se querrian conservar las alertas. En este caso propondria que hubiera un boton de "resolver" (en lugar de eliminar) que lo que hiciera es que la marca como resuelta, y ya no aparece en el listado de alertas a no ser que alguien expresamente quiera verlas.

- Todas (No resueltas): mostraria todas las no resueltas (notas, precaucion, peligro)
- Todas (Incluye resueltas): mostraria todas, incluidas las resueltas
- Notas: mostraria notas no resueltas
- Precacion: mostraria los warnings no resueltos
- Peligro: mostraria las que requieren accion inmediata no resueltas

Las resueltas, ya no aparecerian en el dashboard.

**Comment by joseanrey** [comment]
Perfecto, de hecho si por mí fuera no eliminaría nunca nada y guardaría un versionado de las ediciones de cada dato xD

Me parece bien todo lo que propones, quizá cuando se resuelva una alerta daría la posibilidad de indicar cómo se ha resuelto con un comentario.
