### ISSUE TITLE
Posibles procesos huérfanos

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#32]
Actualmente, si tenemos una persona asociada a un proyecto X y varios procesos añadidos bajo el filtro de ese proyecto, si yo modifico la ficha de persona para asociarla al proyecto Y nos quedan unos cuantos procesos huérfanos. Se siguen mostrando en la lista de procesos "Sin filtrar" pero no puedo editarlos para asociarlos a otro proyecto.

**Comment by mariogarcia** [comment]
Veo varias opciones

1. Deberiamos no permitir desasociar a un usuario de un proyecto sin que reasigne los procesos a otro proyecto al que pertenezca

2. Deberiamos dejar esos procesos asociados al antiguo proyecto, y que se pudieran seguir filtrando por el antiguo proyecto con independencia de que el usuario ya no pertenezca a ese proyecto. Y ademas que se pudieran reasignar los antiguos procesos a proyectos nuevos. Lo unico que no permitiria aunque es obvio es que se pudieran asignar procesos nuevos a proyectos antiguos. 

Yo me quedaria con la opcion 2. En cualquier caso esto es algo importante, ya que como me cuentas deja al sistema inconsistente. Deberiamos darle prioridad y ya que la agenda esta casi terminada meter este problema en la 0.3.0. Que opinas @joseanrey ?

**Comment by joseanrey** [comment]
Si, parece un poco grave si. Estupendo, opción 2 para la 0.3.0. Bien pensado porque si X deja de participar en P es de interés conservar la información de esos procesos aunque ya esté a otra cosa para tener un histórico.
