### ISSUE TITLE
Fallo filtro edad

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#34]
Al filtrar personas por un rango de edades aparecen también las de edad inferior a la edad mínima filtrada.

**Comment by mariogarcia** [comment]
Ok, lo miro.

**Comment by mariogarcia** [comment]
Este error no estoy consiguiendo reproducirlo. Puede ser que haya mas filtros que solo la edad en el caso concreto que me comentas @joseanrey  ?

**Comment by joseanrey** [comment]
No, no tienen ningún otro filtro, solo la edad. Yo creo que lo que puede suceder es que cuando hace el filtrado muestra a todas las personas que tienen X años ahora mismo o los van a tener en el año actual, ya sea porque ya los han cumplido o porque los van a cumplir hasta el 31 de diciembre. Con lo que muestra a personas de edad inferior a la filtrada en este momento, ¿puede ser?

**Comment by mariogarcia** [comment]
ah, eso puede ser, que solo tenga en cuenta el año, voy a tirar de ese hilo :+1:

**Comment by mariogarcia** [comment]
Efectivamente, tenia en cuenta todo el año.
