### ISSUE TITLE
Fallo exportar CSV

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#35]
Muestra Error 500 al exportar en CSV cualquier tipo de listado de personas, filtrado y sin filtrar. La exportación de procesos funciona correctamente.

**Comment by mariogarcia** [comment]
@joseanrey mira a ver si me puedes pegar el log del servidor, que seguro que tiene una bonita traza de error. Mientras intentare reproducirlo en mi maquina.

**Comment by mariogarcia** [comment]
Vale ya se que ha pasado. Sel me olvido modificar la exportacion con los cambios de los campos relacionados con servicios sociales (caiCase).
