### ISSUE TITLE
Propuestas de dashboard

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#38]
De momento, con las funcionalidades que tenemos, se nos ocurren:

- Mantener "Ir a ficha por ID"
- Últimas personas añadidas en general
- Últimos y próximos procesos
- Botones rápidos de añadir persona

**Comment by mariogarcia** [comment]
- Busqueda por ID disponible desde cualquier pantalla (barra de arriba)
- Creacion de una nueva persona disponible desde cualquier pantalla (barra de arriba)
- Ultimas personas agregadas y cuales estan asignadas al usuario logado

![dashboard](https://user-images.githubusercontent.com/1414131/107488861-3b53bd00-6b88-11eb-9cc4-04259a9ac68c.png)
