### ISSUE TITLE
Funcionalidad Informe/Estadísticas

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#39]
El sistema podría mostrar en algún lugar (dashboard quizá) unas estadísticas generales de Liceo que más adelante se podrían ir afinando:
- Personas añadidas en el sistema totales desagregadas por activas/inactivas.
- Personas de las que es responsable un usuario (solo visibles para el usuario logado)
- Número de procesos.
- Número de proyectos.

**Comment by mariogarcia** [comment]
![dashboard](https://user-images.githubusercontent.com/1414131/107489223-abfad980-6b88-11eb-8453-7c062cec86be.png)

- Personas agregadas/activas
- Personas responsables del usuario logado
- Numero de procesos
- Numero de procesos

Esta tarea tiene que ver con la #38

**Comment by joseanrey** [comment]
¡Me parece fetén unir las estadísticas con el dashboard!

Mola mucho, ¿los números de colores son los procesos? ¿qué indican los colores? ¿proyectos?

**Comment by mariogarcia** [comment]
:+1:
