### ISSUE TITLE
Proyectos en Ficha persona

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#42]
No aparecen los proyectos vinculados en la ficha de la persona, únicamente se pueden ver cuando editas la misma. Podría facilitar incluirlos en la zona destacada de la izquierda, con los otros datos relevantes.

**Comment by mariogarcia** [comment]
Sip, me parece bien

**Comment by mariogarcia** [comment]
Lo voy a meter en la 0.4.1 porque es poca cosa
