### ISSUE TITLE
Dashboard: Últimas alertas

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#43]
Me proponen mis compañeros lo siguiente: les gustaría poder ver en el dashboard las personas que tienen asignadas y tienen alerta activa, quizá por orden de importancia aunque el orden no es relevante, ya que hasta ahora pueden verlo pero solo si han sido añadidas recientemente en Liceo.

**Comment by mariogarcia** [comment]
A ver si lo he entendido bien... el problema es que si hay alguien con una alerta roja y no ha sido agregado recientemente puede que no aparezca en el dashboard porque se haya visto desplazada por nuevas incorporaciones. Es eso lo que estas comentando ?

Si es asi, entiendo que ordenando las personas agregadas por numero de alertas os valdria. Es asi ?

**Comment by joseanrey** [comment]
Si, eso es. Las alertas no se pueden ver de un vistazo si no pertenecen a personas recientemente añadidas. 

Otra cosa que se me ocurre es que si hay más personas con alertas que las que se muestran en el listado de personas del dashboard tampoco se verían todas. ¿Podría el usuario pueda filtrar personas también por "las que tienen alerta activa"?

**Comment by mariogarcia** [comment]
Si, **aparte del cambio en el dashboard**, creo que se esta gestando una historia que podriamos llamar "Filtros". Es decir que un usuario pueda guardar busquedas que pueda usar en cualquier momento sin tener que crear una busqueda determinada cada vez. De esa manera la pantalla de listado de persona tendria una forma de guardar una busqueda para poder reusarla en el futuro.

Con eso y **metiendo las alertas en el filtro busqueda**, creo que dariamos mas potencia a los usuarios sin tener que crear vistas especificas.

**Comment by mariogarcia** [comment]
@joseanrey estoy resolviendo esta historia con la siguiente solucion:

- En la **columna de personas agregadas**, se van a ordenar por aquellas personas con mas alertas graves primero
- En la **columna de personas asignadas**, se van a ordernar por aquellas personas asignadas al usuario logado con mas alertas graves primero

No solo se ordena por numero de alertas activas sino tambien se tiene en cuenta que las mas importantes van primero.

Lo de filtrar las personas por alertas esta dado de alta como nueva historia en #46

**Comment by mariogarcia** [comment]
Tendria esta pinta:

![alertas_ordenadas](https://user-images.githubusercontent.com/1414131/108097645-af0f3180-7082-11eb-92ec-b3db27c561c4.png)

**Comment by joseanrey** [comment]
Moola :) Con eso y los filtros apañao!
