### ISSUE TITLE
Descripción de alertas no se muestra completa

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#44]
La descripción de una alerta se corta a los 50 caracteres y luego añade puntos suspensivos, pero no se puede ver el detalle completo de la misma si no eres el autor, únicamente se puede ver el detalle editando la alerta.

Si marco como resuelta una alerta tampoco puedo ver cómo se ha resuelto pese a ser el autor de la misma.

**Comment by mariogarcia** [comment]
Totalmente de acuerdo, hay que ver como mostrar esa informacion. Le doy una vuelta y os cuento

**Comment by mariogarcia** [comment]
Ahora habra un boton para mostrar la alerta sin tener que editarla

![alerts_hover](https://user-images.githubusercontent.com/1414131/108067463-187e4880-7061-11eb-84dd-94bf956634c5.png)

Se mostrara como un modal:

![alerts_show](https://user-images.githubusercontent.com/1414131/108067461-187e4880-7061-11eb-98a4-06b3daf002ef.png)

Y en el caso de que se haya resuelto la alerta, se mostrara ademas quien la resolvio, cuando y el mensaje que introdujo al resolverla.

![alerts_resolved_show](https://user-images.githubusercontent.com/1414131/108067456-17e5b200-7061-11eb-91d0-180ca39ca93d.png)
