### ISSUE TITLE
ID proyecto

### ISSUE THREAD

**Issue by joseanrey** [liceo-social/liceo#5]
La aplicación elige como código de proyecto el primer carácter de cada una de las palabras del nombre del proyecto, si tienes dos proyectos con el mismo número de palabras que comienzan por la misma letra el segundo proyecto añadido se muestra con la misma identificación:

Mi nuevo proyecto 2020 -> MNP2
Mi nuevo proyecto 2021 -> MNP2

**Comment by mariogarcia** [comment]
Vale le echo un vistazo. La idea era evitar mostrar un nombre de proyecto muy largo en las tablas. Podemos hacer esa contracción no tan larga y ademas que si te pones encima te muestre el nombre completo. Que te parece ?

**Comment by joseanrey** [comment]
Si, la idea me parece genial. Era por comentarlo, que puede causar confusión cuando tienes una lista con X personas puede parecer que pertenecen al mismo proyecto. Si queremos que sea sencillo se me ocurre que podamos elegir el código de proyecto y lo introducimos a mano en el formulario de "Nuevo proyecto": Nombre, Código. Lo de mostrar el nombre completo me parece perfecto también.

**Comment by mariogarcia** [comment]
Ah vale, eso me parece bien, que puedas elegir el código del proyecto.
