### ISSUE TITLE
Dentro de un proceso, detalle, volver a listado de procesos. ERROR. 404 

### ISSUE THREAD

**Issue by MacaA2000** [liceo-social/liceo#51]
Cuando estas con un proceso abierto, detalle, y quieres volver al listado de procesos, si pinchas arriba en PROCESOS sale este error.... 

![image](https://user-images.githubusercontent.com/79325214/113706928-80efba80-96df-11eb-840a-c89abe73dcc6.png)

**Comment by mariogarcia** [comment]
Vale esto es un error, seguro que es una tonteria como pasaba en el listado de proyectos. 

Puedes por favor enviarme la direccion web que te aparece en el navegador cuando te sucede esto ? Es para asegurarme de donde mirar. Gracias :)

**Comment by MacaA2000** [comment]
Hola

ahi va

http://192.168.1.100/person/processes/340

**Comment by joseanrey** [comment]
Hay una cosa que nos sucede que quizá está relacionada. Cuando accedes al detalle de un proceso que está en una página determinada del listado de procesos, la página 3 por ejemplo, al "Volver al listado" no regresas a la página 3, sino a la primera página. Sucede lo mismo que debería pasar al hacer click en "Procesos".

**Comment by mariogarcia** [comment]
Vale el error 404 esta arreglado. El enlace al listado de procesos de la persona tanto en el detalle de un proceso como en la edicion estaban mal.

En cuanto a esto ultimo que me comentas @joseanrey efectivamente, el comportamiento actualmente no es como la "flecha del navegador", sino que pulsas la accion de ir al listado. En todo caso para evitar la confusion de momento podemos cambiar el texto a "Ir al listado" en lugar de "Volver al listado"
