### ISSUE TITLE
Mejora del panel de datos personales. 

### ISSUE THREAD

**Issue by MacaA2000** [liceo-social/liceo#52]
Propuesta de mejora, que en algún apartado de los datos personales, por ejemplo en DATOS INTERNOS se puedan configurar según lo que quiera cada entidad algunos aspectos para hacer check y saber que esta persona tiene lo que hemos configurado.

En nuestro caso por ejemplo....

Tiene autorización para poder hacerle fotos
Puede irse solo a casa
......

**Comment by mariogarcia** [comment]
Si, entiendo que es como algo que de un vistazo rapido sabes si hay algo que falta o no. 

Me lo imagino como que en algun sitio, configuras que propiedades de los datos personales agregar en ese TODO list, y una vez configurado, en la pantalla de datos personales te sale esa TODO list diferenciada del resto de datos.

Como te imaginas que se configure esto ? Podria haber en la edicion de los datos de la persona una pestana que pusiera "Ficha Rapida" o "Checks" donde especificaras que propiedades de la persona mostrar en ese panel. Esos datos se verian en el detalle de los datos personales como primer panel visible.

Espero tu feedback

**Comment by MacaA2000** [comment]
Hola

me lo imagino como algo que configuremos como hacemos con los tipos de documentos, o con los tipos de procesos..... que cada entidad pueda editar confirar Que CHECKS quiere que aparezcan en ese espacio .... y que en el panel de la persona aparezcan como un luistado a marcar...

**Comment by MacaA2000** [comment]
Hola

me lo imagino como algo que configuremos como hacemos con los tipos de documentos, o con los tipos de procesos..... que cada entidad pueda editar configurar qué CHECKS quiere que aparezcan en ese espacio .... y que en el panel de la persona aparezcan como un listado a marcar...
