### ISSUE TITLE
Cambios del modelo

### ISSUE THREAD

**Issue by mariogarcia** [liceo-social/liceo#9]
"Caso en ETMF" de tipo cadena de texto en lugar de booleano
"Tiene expediente en CAI" en lugar de "Caso en CAI"
"Caso en CAF" de tipo cadena de texto en lugar de booleano

**Comment by mariogarcia** [comment]
@joseanrey necesito saber si  hay personas que tienen rellenos estos campos y hay que hacer una migracion de datos, o si podemos el modelo sin necesidad de crear esa migracion.

**Comment by joseanrey** [comment]
Hola! No, los hemos dejado en blanco. De ese apartado únicamente están rellenos Centro de servicios sociales y
Trabajador/a social ;)

**Comment by mariogarcia** [comment]
@joseanrey echale un vistazo a como quedaria en la pestana de servicios sociales. Te dejo pantallazo

![liceo_servicios_sociales](https://user-images.githubusercontent.com/1414131/101192286-25db8780-365b-11eb-9409-17481c060a1c.png)

**Comment by joseanrey** [comment]
Hola!

Caso en ETMF sería booleano (checkbox). La etiqueta "Tiene expediente en CAI" sería "Caso en CAI" y "Caso en CAF" sería booleano como ETMF

**Comment by mariogarcia** [comment]
O sea que el enunciado estaba al reves XD

**Comment by joseanrey** [comment]
Jajajajaj Puede ser, según me preguntes, el caso es que la etiqueta da igual mientras sea coherente, lo importante es el tipo de dato.

**Comment by joseanrey** [comment]
Retomo esto ya con más claridad, lo que creo que ha pasado es que la redacción del primer post puede inducir a error:

"Caso en ETMF" es de tipo cadena de texto cuando debería ser booleano
La etiqueta aparece "Tiene expediente en CAI" en lugar de lo que debería aparecer, "Caso en CAI"
"Caso en CAF" es de tipo cadena de texto cuando debería ser booleano

Así todo cuadra con mi comentario de ayer

**Comment by joseanrey** [comment]
Hola @mariogarcia, viendo la demo de la 0.2 retomo este hilo porque se nos quedó un cuadro de texto por ahí perdido jejeje

He aprovechado para detallar más lo que pone en cada etiqueta en el formulario y que sea más didáctico. Además, las he ordenado por orden natural de intervención: Dentro del sistema de protección social primero accedes a Atención Social Primaria, luego si el caso es con infancia y de riesgo se valora y hace seguimiento en los ETMF. A continuación, si es caso tiene indicadores de desprotección (agresiones, violencia hacia niñas y niños, no escolarización, etc) se revisa el caso en el CAI y finalmente puede llegar a la CAF, que ya depende del sistema de protección de la Comunidad de Madrid y valora, por ejemplo, situaciones de guarda temporal o tutela de niñas y niños. 

![SSociales](https://user-images.githubusercontent.com/1851396/102221891-022e0200-3ee3-11eb-9a37-9dee1168c2bb.png)

**Comment by mariogarcia** [comment]
No problem. Pues reabro la issue
